models/Product.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace app\models;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "emily_product".
 *
 *  @author Rost
 */

class Product extends ActiveRecord {
   public static function tableName() {
        return 'emily_product';
    }
    
    public function getTyps() {
        return $this->hasOne(Type::className(), ['idType' => 'type_idType']);
    }
}

controllers/CartController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * 
 */

namespace app\controllers;
use app\controllers\AppController;
use app\models\Product;
use app\models\Cart;
use Yii;
use app\models\Order;
use app\models\OrderItems;
use \app\models\Cities;
use \app\models\EmilyOfficeNP;
use \app\models\DostavkaNP;
use \app\models\InternetDocument;
/**
 * Class CartController to control the behavior of the basket of the website and order confirmation
 *
 * @author Rost
 * 
 * 
 * Array 
 * (
 * [1] => Array (
 *      [qty] => QTY,
 *      [name] => Name,
 *      [price] => Price,
 *      [img] => Img
 * )
 * [10] => Array (
 *      [qty] => QTY,
 *      [name] => Name,
 *      [price] => Price,
 *      [img] => Img
 * )
 * [qty] => QTY,
 * [sum] => Sum
 * )
 */
class CartController extends AppController{
    
     /**
     * Add action of adding a product to cart.
     * @var int $id the product ID obtained from get request
     * @var int $qty the number of products obtained from get request
     * @var array $product the product from the database
     * @return cart-modal
     * @see Cart
     */
    public function actionAdd() {
        $id = Yii::$app->request->get('id');
        $qty = (int) Yii::$app->request->get('qty');
        $qty = !$qty ? 1 : $qty;
        $product = Product::findOne($id);
        if(empty($product)) return false;
        
        $session = Yii::$app->session;
        $session->open();
        
        $cart = new Cart();
        
      $cart->addToCart($product, $qty);
       if(!Yii::$app->request->isAjax) {
           return $this->redirect(Yii::$app->request->referrer);
       }
      $this->layout = FALSE;
      return $this->render('cart-modal', compact('session'));
    }
    
    /**
     * Action to empty the Cart
     * @return cart-modal
     */
    public function actionClear() {
            $session = Yii::$app->session;
            $session->open();
            $session->remove('cart');
             $session->remove('cart.qty');
              $session->remove('cart.sum');
              $this->layout = FALSE;
      return $this->render('cart-modal', compact('session'));
    }
    /**
     * Action to delete an item (product) in the cart
     * @return cart-modal
     */
    public function actionDelItem() {
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        $this->layout = FALSE;
        return $this->render('cart-modal', compact('session'));
    }
     /**
     * Action to delete an item (product) in the shopping cart on the order page
     * @return $this->redirect(Yii::$app->request->referrer)
     */
      public function actionDelItemOrder() {
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        $this->layout = FALSE;
        
           return $this->redirect(Yii::$app->request->referrer);
      
    }
    
    /**
     * Action show Cart 
     * @return cart-modal
     */
    public function actionShow() {
        $session = Yii::$app->session;
        $session->open();
        $this->layout = FALSE;
        return $this->render('cart-modal', compact('session'));
    }
    /**
     * Action of page output order
     * @see page order view
     */
    public function actionView() {
     
       $session = Yii::$app->session;
        $session->open();
        
        $this->setMeta('EMILY | Кошик');
        
        $order = new Order();
        $dostavka = new DostavkaNP();
        $cities = new Cities();
        $office = new EmilyOfficeNP();
        
        if($order->load(Yii::$app->request->post())) {
            $order->qty = $session['cart.qty'];
            $order->sum = $session['cart.sum'];
            $order->dostavka = "samovivoz";
            $order->addressUser = "no";
            if($order->save()) {
                $this->saveOrderItems($session['cart'], $order->id);
                Yii::$app->session->setFlash('success_order', 'Ваше замовлення прийняте!');
                
             //send an email with the order | cartOrder the view the content of the email
      /*          Yii::$app->mailer->compose('cartOrder', compact('session', 'order'))
                        ->setFrom('ros.tan0601@gmail.com')
                        ->setTo($order->emailUser)
                        ->setSubject('Замовлення № '. $order->id)
                        ->send();
       * 
       */
                //remove the cart from the session
                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                
                return $this->refresh();
                }
            else {
                Yii::$app->session->setFlash('error_order', 'Замовлення не може бути прийняте! (помилка при оформленні) ');
            }
         
         
        }
        return $this->render('view', compact('session', 'order', 'cities', 'office', 'dostavka'));
    }
    
     public function actionViewnp() {
       
        $cityID = Yii::$app->request->get('id');
        $city = Cities::getCityID($cityID);
        $ref = $city->ref;
        $office = EmilyOfficeNP::find()->asArray()->where(['cityRef' => $ref])->all();
        
      
        $this->layout = FALSE;
        return $this->render('select', compact('office'));
        
     }
     
     /**
      * Save order if you choose the delivery
      * @see page order view
      */
     
     public function  actionOrdernp() {
         
        
            $session = Yii::$app->session;
            $session->open();
            $order = new Order();
            $cities = new Cities();
            $office = new EmilyOfficeNP();
            $dostavka = new DostavkaNP();
            $ar = Yii::$app->request->post();
            if($order->load($ar) && $cities->load($ar) 
                    && $office->load($ar) && $dostavka->load($ar)) 
                {
                 $order->qty = $session['cart.qty'];
                $order->sum = $session['cart.sum'];
                $order->dostavka = "NovaPoshta";
                $order->nameUser = $dostavka->contactUser;
                $order->phoneUser = $dostavka->phoneUser;
             $r = EmilyOfficeNP::getOfficeKey($office->description);
                $order->addressUser = $r['description'];
             
            if($order->save()) {
                     
                     $this->saveOrderItems($session['cart'], $order->id);
                      $dostavka->idOrder = $order->id;
                      $dostavka->cityFrom = "db5c88f5-391c-11dd-90d9-001a92567626";
                      $dostavka->cityTo = $cities->description;
                      $dostavka->officeNP = $office->description;
                       
                      $dostavka->contactUser = mb_convert_case($dostavka->contactUser, MB_CASE_TITLE);
                                       
                      $dostavka->save();
                     
                     $this->createEN($order->id, $order->sum, $ar);
                
             
                return $this->refresh();    
                 }
                 else {
                Yii::$app->session->setFlash('error_order', 'Замовлення не може бути прийняте! (помилка при оформленні) ');
            }
            }
            return $this->render('view', compact('session', 'order', 'cities', 'office', 'dostavka'));
                  
     }

          /**
     * Save the order elements in the database
     * @param array $items the cart
     * @param int $order_id the ID order
     */
    protected function saveOrderItems($items, $order_id) {
        
        foreach ($items as $id => $item) {
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['name'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['qty'];
            $order_items->sum_item = $item['qty'] * $item['price'];
            $order_items->save();
        }
    }
    /**
     * Save Internet Document in the database
     * @param int $id the id order
     * @param int $summ the summ order (Cost)
     * @param array $order 
     * 
     */
    
    protected function createEN($id, $summ, $order){
         $city = Cities::getCityID($order['Cities']['description']);
         $cityName = $city->description;
         $office = EmilyOfficeNP::getOfficeKey($order['EmilyOfficeNP']['description']);
         $address = $office->number;
         $nameUser = $order['DostavkaNP']['contactUser'];
         $phone = (string)$order['DostavkaNP']['phoneUser'];
    
        $sendArray = DostavkaNP::arrayEN($summ, $cityName, $address, $nameUser, $phone);
        
         $result = DostavkaNP::createEN($sendArray);
        
         $document = new InternetDocument();
         $document->Ref = $result['data'][0]['Ref'];
         $document->CostOnSite = $result['data'][0]['CostOnSite'];
         $document->EstimatedDeliveryDate = $result['data'][0]['EstimatedDeliveryDate'];
         $document->IntDocNumber = $result['data'][0]['IntDocNumber'];
         $document->TypeDocument = $result['data'][0]['TypeDocument'];
         $document->idOrder = $id;
         if($document->save()) {
              Yii::$app->session->setFlash('success_order', 'Ваше замовлення прийняте! Вартість доставки приблизно '."$document->CostOnSite грн.");
                    $session = Yii::$app->session;
                    $session->open();
                 
                   $session->remove('cart');
                   $session->remove('cart.qty');
                   $session->remove('cart.sum');
         }

controllers/ProductController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace app\controllers;
use app\controllers\AppController;
use app\models\Product;
use Yii;
/**
 * Description of ProductController
 *
 * @author Rost
 */
class ProductController extends AppController {
     /**
     * Displays a page with information about the product.
     * 
     * @return mixed
     */
     public function actionInfo() {
        $id = Yii::$app->request->get('id');
        $product = Product::findOne($id);
        if(empty($product)) throw new \yii\web\HttpException(404, 'Такого товара нет!');
         $this->setMeta('EMILY | Інфо ' . $product->nameProduct);
        
        return $this->render('info', compact('product'));
    }
}

views/product/info.php


   <!-- navbar -->
	<nav class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#NavCol">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         <a class="navbar-brand bg-primary" href="<?= \yii\helpers\Url::to(['/site/login'])?>">ВХІД</a>
        </div>
        <?php if(!Yii::$app->user->isGuest):?>
        <div class="logout">
            	<a  href="<?= \yii\helpers\Url::to(['/site/logout'])?>"><i class="fa fa-user"></i>
	<?= Yii::$app->user->identity['nameUsers']?> Выход</a><br/>
         </div>
            <?php endif;?>
        <?php if(!Yii::$app->user->isGuest):?>
            <div class="enter-admin">
                <a class="navbar-brand bg-primary"  href="<?= \yii\helpers\Url::to(['/admin'])?>" title="Вхід">Адмінка</i></a>
                
            </div>
            <?php endif;?>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="NavCol1">
         <ul class="nav navbar-nav1 navbar-right">
           
            <li><a href="<?= \yii\helpers\Url::to(['/'])?>">Головна</a></li>
            <li><a href="<?= \yii\helpers\Url::to(['/#work'])?>" >Мої вироби</a></li>
            
          </ul>
        <div class="cart">
                <a href="/cart/show" class="cart-img" title="Кошик" onclick="return getCart()"><img src="/images/basket.gif"></a>
       
            </div>
         
        </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
	  
<div class="main clearfix page">

    <div class="product-info clearfix">
        <h1><?= $product->nameProduct?></h1>
        <div class="info-left">
            <div class="info-img">
             <?= \yii\helpers\Html::img("@web/images/portfolio/{$product->namePhoto}", ['alt' => $product->namePhoto]) ?>
           </div>
                
            <div class="info-type"><p>Вид виробу: <?= $product->typs->nameType?></p></div>
        </div>
        
        <div class="info-right">
            <div class="info-description"> 
              <p>
                     <?= $product->description?>
              </p>
          </div>
           
            <div class="info-price">
                     <h2>Вартість: 
                     <?= $product->priceProduct?> грн.
                     </h2>
                <h3>Кількість: <input type="number" min="1" max="20" value="1" id="qty"></h3>
          </div>
            
        
        </div>
        
          
        
        <div class="clear">
           
        </div>
        <div class="link-add">
            <a href="<?= \yii\helpers\Url::to(['/cart/add', 'id' => $product->idProduct])?>" class="add-to-cart addCart"  data-id ="<?= $product->idProduct?>">Додати в кошик</a>  
        
        </div>
        
        
    </div>

</div>
    <!--contact-->
    <div id="contact" class="page page-bgcolor">
		<div class="container">
		<div class="row">
          <div class="col-md-10  col-md-offset-1">
		    <div class="build title-page">
				<h2 class="text-center">Контакти</h2>	
				<div class="line-title bg-primary"></div>
			</div>
		   </div><!-- end col -->
		</div><!-- end row -->
	  	<div class="row">
			<div class="col-md-4 ">
				<div class="build contact clearfix text-center">
					<span class="fa fa-map-marker"></span>
						<p>вул. Шевченка<br />м. Львів, Україна<p>
				</div>			
			</div><!-- end col -->
			<div class="col-md-4 ">
				<div class="build contact clearfix text-center">
					<span class="fa fa-phone"></span>
					
					<p>mob.<a href="tel:+3 8 097 738 46 52">+380977384652</a></p>
					
				</div>
			</div>
			<div class="col-md-4 ">
				<div class="build contact clearfix text-center">
					<span class="fa fa-envelope"></span>
					<p>ros-gap601@yandex.ru</p>
					<p>liliya@emily.hol.es</p>
				</div>
			</div>
		</div><!-- end row -->
	
	  </div><!-- end container -->
	</div>

