models/Cart.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * This is the model class for to control the Cart.
 *
 * @property string $id
 * @property int $qty
 * @property array $product
 */

class Cart extends ActiveRecord {
    
    
    public function addToCart($product, $qty= 1) {
        if(isset($_SESSION['cart'][$product->idProduct])) {
            $_SESSION['cart'][$product->idProduct]['qty'] += $qty;
            
        } else {
            $_SESSION['cart'][$product->idProduct] = [
                'qty' => $qty,
                'name' => $product->nameProduct,
                'price' => $product->priceProduct,
                'img' => $product->namePhoto
            ];
        }
        $_SESSION['cart.qty'] = isset($_SESSION['cart.qty'])? $_SESSION['cart.qty'] + $qty : $qty;
        $_SESSION['cart.sum'] = isset($_SESSION['cart.sum'])? $_SESSION['cart.sum'] + $qty * $product->priceProduct : $qty * $product->priceProduct;
    } 
    
    public function recalc($id) {
       
         if(!isset($_SESSION['cart'][$id])) return false;
         $qtyMinus = $_SESSION['cart'][$id]['qty'];
         $sumMinus = $_SESSION['cart'][$id]['qty'] *  $_SESSION['cart'][$id]['price'];
         $_SESSION['cart.qty'] -= $qtyMinus;
         $_SESSION['cart.sum'] -= $sumMinus;
         unset($_SESSION['cart'][$id]);
         
    }
}

controllers/CartController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * 
 */

namespace app\controllers;
use app\controllers\AppController;
use app\models\Product;
use app\models\Cart;
use Yii;
use app\models\Order;
use app\models\OrderItems;
use \app\models\Cities;
use \app\models\EmilyOfficeNP;
use \app\models\DostavkaNP;
use \app\models\InternetDocument;
/**
 * Class CartController to control the behavior of the basket of the website and order confirmation
 *
 * @author Rost
 * 
 * 
 * Array 
 * (
 * [1] => Array (
 *      [qty] => QTY,
 *      [name] => Name,
 *      [price] => Price,
 *      [img] => Img
 * )
 * [10] => Array (
 *      [qty] => QTY,
 *      [name] => Name,
 *      [price] => Price,
 *      [img] => Img
 * )
 * [qty] => QTY,
 * [sum] => Sum
 * )
 */
class CartController extends AppController{
    
     /**
     * Add action of adding a product to cart.
     * @var int $id the product ID obtained from get request
     * @var int $qty the number of products obtained from get request
     * @var array $product the product from the database
     * @return cart-modal
     * @see Cart
     */
    public function actionAdd() {
        $id = Yii::$app->request->get('id');
        $qty = (int) Yii::$app->request->get('qty');
        $qty = !$qty ? 1 : $qty;
        $product = Product::findOne($id);
        if(empty($product)) return false;
        
        $session = Yii::$app->session;
        $session->open();
        
        $cart = new Cart();
        
      $cart->addToCart($product, $qty);
       if(!Yii::$app->request->isAjax) {
           return $this->redirect(Yii::$app->request->referrer);
       }
      $this->layout = FALSE;
      return $this->render('cart-modal', compact('session'));
    }
    
    /**
     * Action to empty the Cart
     * @return cart-modal
     */
    public function actionClear() {
            $session = Yii::$app->session;
            $session->open();
            $session->remove('cart');
             $session->remove('cart.qty');
              $session->remove('cart.sum');
              $this->layout = FALSE;
      return $this->render('cart-modal', compact('session'));
    }
    /**
     * Action to delete an item (product) in the cart
     * @return cart-modal
     */
    public function actionDelItem() {
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        $this->layout = FALSE;
        return $this->render('cart-modal', compact('session'));
    }
     /**
     * Action to delete an item (product) in the shopping cart on the order page
     * @return $this->redirect(Yii::$app->request->referrer)
     */
      public function actionDelItemOrder() {
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        $this->layout = FALSE;
        
           return $this->redirect(Yii::$app->request->referrer);
      
    }
    
    /**
     * Action show Cart 
     * @return cart-modal
     */
    public function actionShow() {
        $session = Yii::$app->session;
        $session->open();
        $this->layout = FALSE;
        return $this->render('cart-modal', compact('session'));
    }
    /**
     * Action of page output order
     * @see page order view
     */
    public function actionView() {
     
       $session = Yii::$app->session;
        $session->open();
        
        $this->setMeta('EMILY | Кошик');
        
        $order = new Order();
        $dostavka = new DostavkaNP();
        $cities = new Cities();
        $office = new EmilyOfficeNP();
        
        if($order->load(Yii::$app->request->post())) {
            $order->qty = $session['cart.qty'];
            $order->sum = $session['cart.sum'];
            $order->dostavka = "samovivoz";
            $order->addressUser = "no";
            if($order->save()) {
                $this->saveOrderItems($session['cart'], $order->id);
                Yii::$app->session->setFlash('success_order', 'Ваше замовлення прийняте!');
                
             //send an email with the order | cartOrder the view the content of the email
      /*          Yii::$app->mailer->compose('cartOrder', compact('session', 'order'))
                        ->setFrom('ros.tan0601@gmail.com')
                        ->setTo($order->emailUser)
                        ->setSubject('Замовлення № '. $order->id)
                        ->send();
       * 
       */
                //remove the cart from the session
                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                
                return $this->refresh();
                }
            else {
                Yii::$app->session->setFlash('error_order', 'Замовлення не може бути прийняте! (помилка при оформленні) ');
            }
         
         
        }
        return $this->render('view', compact('session', 'order', 'cities', 'office', 'dostavka'));
    }
    
     public function actionViewnp() {
       
        $cityID = Yii::$app->request->get('id');
        $city = Cities::getCityID($cityID);
        $ref = $city->ref;
        $office = EmilyOfficeNP::find()->asArray()->where(['cityRef' => $ref])->all();
        
      
        $this->layout = FALSE;
        return $this->render('select', compact('office'));
        
     }
     
     /**
      * Save order if you choose the delivery
      * @see page order view
      */
     
     public function  actionOrdernp() {
         
        
            $session = Yii::$app->session;
            $session->open();
            $order = new Order();
            $cities = new Cities();
            $office = new EmilyOfficeNP();
            $dostavka = new DostavkaNP();
            $ar = Yii::$app->request->post();
            if($order->load($ar) && $cities->load($ar) 
                    && $office->load($ar) && $dostavka->load($ar)) 
                {
                 $order->qty = $session['cart.qty'];
                $order->sum = $session['cart.sum'];
                $order->dostavka = "NovaPoshta";
                $order->nameUser = $dostavka->contactUser;
                $order->phoneUser = $dostavka->phoneUser;
             $r = EmilyOfficeNP::getOfficeKey($office->description);
                $order->addressUser = $r['description'];
             
            if($order->save()) {
                     
                     $this->saveOrderItems($session['cart'], $order->id);
                      $dostavka->idOrder = $order->id;
                      $dostavka->cityFrom = "db5c88f5-391c-11dd-90d9-001a92567626";
                      $dostavka->cityTo = $cities->description;
                      $dostavka->officeNP = $office->description;
                       
                      $dostavka->contactUser = mb_convert_case($dostavka->contactUser, MB_CASE_TITLE);
                                       
                      $dostavka->save();
                     
                     $this->createEN($order->id, $order->sum, $ar);
                
             
                return $this->refresh();    
                 }
                 else {
                Yii::$app->session->setFlash('error_order', 'Замовлення не може бути прийняте! (помилка при оформленні) ');
            }
            }
            return $this->render('view', compact('session', 'order', 'cities', 'office', 'dostavka'));
                  
     }

          /**
     * Save the order elements in the database
     * @param array $items the cart
     * @param int $order_id the ID order
     */
    protected function saveOrderItems($items, $order_id) {
        
        foreach ($items as $id => $item) {
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['name'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['qty'];
            $order_items->sum_item = $item['qty'] * $item['price'];
            $order_items->save();
        }
    }
    /**
     * Save Internet Document in the database
     * @param int $id the id order
     * @param int $summ the summ order (Cost)
     * @param array $order 
     * 
     */
    
    protected function createEN($id, $summ, $order){
         $city = Cities::getCityID($order['Cities']['description']);
         $cityName = $city->description;
         $office = EmilyOfficeNP::getOfficeKey($order['EmilyOfficeNP']['description']);
         $address = $office->number;
         $nameUser = $order['DostavkaNP']['contactUser'];
         $phone = (string)$order['DostavkaNP']['phoneUser'];
    
        $sendArray = DostavkaNP::arrayEN($summ, $cityName, $address, $nameUser, $phone);
        
         $result = DostavkaNP::createEN($sendArray);
        
         $document = new InternetDocument();
         $document->Ref = $result['data'][0]['Ref'];
         $document->CostOnSite = $result['data'][0]['CostOnSite'];
         $document->EstimatedDeliveryDate = $result['data'][0]['EstimatedDeliveryDate'];
         $document->IntDocNumber = $result['data'][0]['IntDocNumber'];
         $document->TypeDocument = $result['data'][0]['TypeDocument'];
         $document->idOrder = $id;
         if($document->save()) {
              Yii::$app->session->setFlash('success_order', 'Ваше замовлення прийняте! Вартість доставки приблизно '."$document->CostOnSite грн.");
                    $session = Yii::$app->session;
                    $session->open();
                 
                   $session->remove('cart');
                   $session->remove('cart.qty');
                   $session->remove('cart.sum');
         }

controllers/ProductController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace app\controllers;
use app\controllers\AppController;
use app\models\Product;
use Yii;
/**
 * Description of ProductController
 *
 * @author Rost
 */
class ProductController extends AppController {
     /**
     * Displays a page with information about the product.
     * 
     * @return mixed
     */
     public function actionInfo() {
        $id = Yii::$app->request->get('id');
        $product = Product::findOne($id);
        if(empty($product)) throw new \yii\web\HttpException(404, 'Такого товара нет!');
         $this->setMeta('EMILY | Інфо ' . $product->nameProduct);
        
        return $this->render('info', compact('product'));
    }
}

views/cart/cart-modal.php
<?php use yii\helpers\Html;?>
<?php if(!empty($session['cart'])): ?>

    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Фото</th>
                    <th>Назва</th>
                    <th>Кількість</th>
                    <th>Ціна</th>
                    <th><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($session['cart'] as $id=>$item):?>
                 <tr>  
                     <td><?=
                     Html::img("@web/images/portfolio/{$item['img']}", ['alt' => "{$item['name']}", 'class' => 'cart-modal-img', 'width' => '50px']);
                     ?></td>
                     <td><?= $item['name']?></td>
                      <td><?= $item['qty']?></td>
                       <td><?= $item['price']?></td>
                       <td><span data-id="<?= $id?>" class="del-item glyphicon glyphicon-remove text-danger" aria-hidden="true"></span></td>
               
                  </tr> 
                <?php endforeach;?>
                  <tr>
                      <td colspan="4">Итого:</td>
                      <td><?= $session['cart.qty']?> шт.</td>
                  </tr>
                   <tr>
                      <td colspan="4">На сумму:</td>
                      <td><?= $session['cart.sum']?> грн.</td>
                  </tr>
            </tbody>
            
        </table>
</div>

<?php else: ?>
<h3>Кошик порожній!</h3>
<?php endif; ?>

views/cart/internetDocument.php
<?php


$res = Array(
        "apiKey" => "505c0b389f71f705bd081d753e9378b7",
        "modelName" => "InternetDocument",
        "calledMethod" => "save",
        "methodProperties" => [
         "NewAddress" => "1",
        "PayerType" => "Recipient",
        "PaymentMethod" => "Cash",
        "CargoType" => "Cargo",
        "Weight" => "0.5",
        "ServiceType" => "WarehouseWarehouse",
        "SeatsAmount"=> "1",
        "Description"=> "Інше",
        "Cost"=> "$summ",
        "CitySender"=> "db5c88f5-391c-11dd-90d9-001a92567626",
        "Sender"=> "630b61e9-fe4d-11e6-8ba8-005056881c6b",
        "SenderAddress"=> "16922806-e1c2-11e3-8c4a-0050568002cf",
        "ContactSender"=> "ebdaa999-010b-11e7-8ba8-005056881c6b",
        "SendersPhone"=> "380991234567",
        "RecipientCityName"=> "$cityName",
        "RecipientArea"=> "",
        "RecipientAreaRegions"=> "",
        "RecipientAddressName"=> "$address",
        "RecipientHouse"=> "",
        "RecipientFlat"=> "",
        "RecipientName"=> "$nameUser",
        "RecipientType"=> "PrivatePerson",
        "RecipientsPhone"=> "$phone"
        ],
);


/*

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'http://testapi.novaposhta.ua/v2.0/json/Address/getCities');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, Array("Content-Type: application/json"));
		curl_setopt($ch, CURLOPT_HEADER, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
		curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($res));
		curl_setopt($ch, CURLOPT_POST, 1);
		
		$response = curl_exec($ch);
		curl_close($ch);
                
                $result = is_array($response)
				? $response
				: json_decode($response, 1);
		
	
                
                Cities::deleteAll();
                
                $n = 1;	
                foreach ($result['data'] as $key=> $val) {
                           
			 $cities = new Cities();
                         $cities->id = $n;
                         $cities->description = $val['Description'];
                         $cities->descriptionRu = $val['DescriptionRu'];
                         $cities->ref = $val['Ref'];
                         $cities->area = $val['Area'];
                         $cities->cityID = $val['CityID'];
                         $cities->save();
                         ++$n;
		};
         
        Yii::$app->getResponse()->redirect('/admin');
 * 
 * 
 */

views/cart/select.php
<select>
    <?php foreach ($office as $k => $v):?>
    <option value="<?= $v['siteKey']?>"><?= $v['description']?></option>
    <?php endforeach;?>
</select>

views/cart/view.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;


?>

<!-- navbar -->
	<nav class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#NavCol">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         <a class="navbar-brand bg-primary" href="<?= \yii\helpers\Url::to(['/site/login'])?>">ВХІД</a>
        </div>
        <?php if(!Yii::$app->user->isGuest):?>
        <div class="logout">
            	<a  href="<?= \yii\helpers\Url::to(['/site/logout'])?>"><i class="fa fa-user"></i>
	<?= Yii::$app->user->identity['nameUsers']?> Выход</a><br/>
         </div>
            <?php endif;?>
        <?php if(!Yii::$app->user->isGuest):?>
            <div class="enter-admin">
                <a class="navbar-brand bg-primary"  href="<?= \yii\helpers\Url::to(['/admin'])?>" title="Вхід">Адмінка</i></a>
                
            </div>
            <?php endif;?>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="NavCol1">
         <ul class="nav navbar-nav1 navbar-right">
           
            <li><a href="<?= \yii\helpers\Url::to(['/'])?>">Головна</a></li>
            <li><a href="<?= \yii\helpers\Url::to(['/#work'])?>" >Мої вироби</a></li>
            
          </ul>
        <div class="cart">
                <a href="/cart/show" class="cart-img" title="Кошик" onclick="return getCart()"><img src="/images/basket.gif"></a>
       
            </div>
         
        </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

<div class="page222 main clearfix page">
   
<div class="container">
    <div>
         <?php if( Yii::$app->session->hasFlash('success_order') ): //вывод сообщения успешного сохранения товара?>
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo Yii::$app->session->getFlash('success_order'); ?>
        </div>
    <?php endif;?>

    <?php if( Yii::$app->session->hasFlash('error_order') ): //вывод в случае ошибки сохранения заказа?>
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo Yii::$app->session->getFlash('error_order'); ?>
        </div>
    <?php endif;?>
    </div>
    
    <?php if(!empty($session['cart'])): ?>

    <div id="cart-order" class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Фото</th>
                    <th>Назва</th>
                    <th>Кількість</th>
                    <th>Ціна</th>
                    <th>Сумма</th>
                    <th><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($session['cart'] as $id=>$item):?>
                 <tr>  
                     <td><?=
                     Html::img("@web/images/portfolio/{$item['img']}", ['alt' => "{$item['name']}", 'class' => 'cart-modal-img', 'width' => '50px']);
                     ?></td>
                     <td><a href="<?= Url::to(['product/info', 'id'=>$id])?>"><?= $item['name']?></a></td>
                      <td><?= $item['qty']?></td>
                       <td><?= $item['price']?></td>
                        <td><?= $item['price'] * $item['qty']?></td>
                        <td><a href="<?= Url::to(['cart/del-item-order', 'id'=>$id])?>"><span class="del-item glyphicon glyphicon-remove text-danger" aria-hidden="true"></span></a></td>
               
                  </tr> 
                <?php endforeach;?>
                  <tr>
                      <td colspan="4">Итого:</td>
                      <td><?= $session['cart.qty']?> шт.</td>
                      <td></td>
                  </tr>
                   <tr>
                      <td colspan="4">На сумму:</td>
                      <td><?= $session['cart.sum']?> грн.</td>
                       <td></td>
                  </tr>
            </tbody>
            
        </table>
</div>
    
    <hr />
  <h2>Виберіть спосіб доставки:</h2>
    <div type="submit" id="smv" onclick="showSm()" class="btn btn-success">Самовивіз</div>
    <div type="submit" id="np"  onclick="showNp()" class="btn btn-success">Нова Пошта</div>
   
    <div id="deliv" style="display:none">   
    <?php $form = ActiveForm::begin(['id' => 'samov'])?>
       <h2>Для оформлення замовлення, заповніть всі поля:</h2> 
    <?= $form->field($order, 'nameUser')->textInput(['id' => 'nameSam'])?>
    <?= $form->field($order, 'emailUser')->input('email')->textInput(['id' => 'emailSam'])?>
    <?= $form->field($order, 'phoneUser')->widget(\yii\widgets\MaskedInput::className(), [
    'name' => 'phone',
    'mask' => '389999999999',
])?>
    
     <hr />
   
    
        <h2>Вид доставки: самовивіз</h2>
        <?= Html::submitButton('Замовити', ['class' => 'btn btn-success', 'formaction' => '/cart/view'])?>
        <?php ActiveForm::end()?>
    </div>
        
     <div id="nevpost" style="display:none">
          <?php $formn = ActiveForm::begin(['id' => 'nevpost'])?>
         
         <h5>Для отримання замовлення введіть П.І.Б. контактної особи (повністю)</h5>
         
          <?= $formn->field($dostavka, 'contactUser')?>
         <?= $formn->field($order, 'emailUser')->input('email')?>
    <?= $formn->field($dostavka, 'phoneUser')->widget(\yii\widgets\MaskedInput::className(), [
         'name' => 'phoneNP',
        'mask' => '380999999999',
])?>
         <h5>Виберіть місто і відділення</h5>
    
    <?= $formn->field($cities, 'description')->dropDownList(
 \yii\helpers\ArrayHelper::map(app\models\Cities::find()->all(), 'cityID', 'description'), 
            
            ['prompt'=>'Виберіть місто', 'onchange' => 'getCont()', 'id'=>'getcities']
    )?>
   
        
       <?= $formn->field($office, 'description')->dropDownList(
                ['0'=>'Виберіть відділення']
               )?>  
    
     <?= Html::submitButton('Замовити', ['class' => 'btn btn-success', 'formaction' => '/cart/ordernp'])?>
   
   
    </div>   
        
      
    <?php ActiveForm::end()?>
    
    </div>
    
<?php else: ?>
<h3>Кошик порожній!</h3>
<?php endif; ?>
    

</div>
 


</div>
 

<div id="contact" class="page page-bgcolor">
		<div class="container">
		<div class="row">
          <div class="col-md-10  col-md-offset-1">
		    <div class="build title-page">
				<h2 class="text-center">Контакти</h2>	
				<div class="line-title bg-primary"></div>
			</div>
		   </div><!-- end col -->
		</div><!-- end row -->
	  	<div class="row">
			<div class="col-md-4 ">
				<div class="build contact clearfix text-center">
					<span class="fa fa-map-marker"></span>
						<p>вул. Шевченка<br />м. Львів, Україна<p>
				</div>			
			</div><!-- end col -->
			<div class="col-md-4 ">
				<div class="build contact clearfix text-center">
					<span class="fa fa-phone"></span>
					
					<p>mob.<a href="tel:+3 8 097 738 46 52">+380977384652</a></p>
					
				</div>
			</div>
			<div class="col-md-4 ">
				<div class="build contact clearfix text-center">
					<span class="fa fa-envelope"></span>
					<p>ros-gap601@yandex.ru</p>
					<p>liliya@emily.hol.es</p>
				</div>
			</div>
		</div><!-- end row -->
	
	  </div><!-- end container -->
	</div>